#!/bin/bash
# Program with menu

DELAY=3

while [[ "$REPLY" != 0  ]]; do
    clear
    echo "
DOCKER INSTALLATOR

	==========================================

	1. Docker 
	2. Docker Compose
	3. Docker Swarm
	0. Exit

	==========================================
    
	"

    read -p "Please select what do you want to install, press  0-3 and Enter: "

    if [[ $REPLY =~ ^[0-3]$ ]]; then
		
    if [[ $REPLY == 1 ]]; then
        echo "Installing Docker..."
	echo "Updating system... "
        sudo apt-get update -y
	echo -e "\nDownloading and adding docker public key"

        wget -O docker.gpg https://download.docker.com/linux/debian/gpg
	sudo apt-key add docker.gpg
	
	echo -e "\nAdding repository"
        echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu/ $(lsb_release -cs) stable" \
	|  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

#	cat /etc/os-release | grep VERSION_CODENAME | cut -d "=" -f 2 <== same as lsb_release -cs
        echo "Installing Docker"
	sudo apt-get update -y
	sudo apt-get install docker-ce -y
	echo -e "\nCompleted succesfully."
        docker --version
        sleep "$DELAY"
        continue
    fi	
				
    if [[ $REPLY == 2 ]]; then
        echo "Installing Docker-Compose"
        sudo apt-get update -y
        echo -e "\nCompleted succesfully."
        sleep "$DELAY"
        continue
    fi
    if [[ $REPLY == 3 ]]; then
        echo "Installing Docker Swarm"
	sudo apt-get update -y
	echo -e "\nCompleted sucessfully."
        sleep "$DELAY"
        continue
    fi
    else
        echo "Invalid input."
        sleep "$DELAY"
    fi

done
echo -e  "\nProgram terminated."

