#!/bin/bash

# Program with menu

clear
echo "
	
	1. option1
	2. option2
	3. oprion3
	0. Exit
"
read -p "Please select option from 0-3 and press Enter:"

while [[ $REPLY != 0 ]]; do
	if [[ $REPLY == 1 ]]; then
		echo "opt1"
		exit
	elif [[ $REPLY == 2 ]]; then
		echo "opt2"
                exit
	elif [[ $REPLY == 3 ]]; then
		echo "opt3"
		exit
	fi
done
