#!/bin/bash

echo "Please enter an intriger: ->"
read int

if [[ "$int" =~ ^-?[0-9]+$ ]]; then
    if [ "$int" -eq 0 ]; then
	    echo "'$int' is 0."
    elif [ "$int" -lt 0 ]; then
	    echo "'$int' is negative. "
    else
	    echo "'$int' is positive."
    fi
    if [ $((int % 2)) -eq 0 ]; then
	echo "$int is even."
    else
        echo "$int is odd."
    fi	
else
    echo "'$INT' in not an int." 
	return 1
fi

