#!/bin/bash

invalid_input() {
	echo "Invalid input $REPLY " >&2
}

read -p "Enter a single item --> "

# input empty (invalid)
[[ -z "$REPLY" ]] && invalid_input

# input has multilines (invalid)
(( "$(echo $REPLY | wc -w)" > 1 )) && invalid_input

if [[ $REPLY =~ ^[-[:alnum:]\._]+$ ]]; then
	echo "$REPLY is a valid filename."
	if [[ -e "$REPLY" ]]; then
		echo "And file $REPLY exist."
	else 
		echo "However, file $REPLY does not exists."
	fi

	if [["$REPLY" =~ ^-?[[:digit:]]*\.[[:digit:]]+$  ]]; then
		echo "$REPLY is a floating point number"
	
	else 
		echo "$REPLY is not valid "
	fi
	if [[ "$REPLY" =~ ^-?[[:digit:]]+$ ]]; then
		echo "$REPLY is integer"
	else
		echo "$REPLY is not integer"
	fi
else 
	echo "The string $REPLY is not valid."
fi
	

